/**
 * Generates `docs/protocol.md` from the protocol's zod schemas. Run with
 * `pnpm -F @shellbell/protocol gen:protocol-doc`. Deterministic: running it twice with no schema
 * change produces a byte-identical file, so the generated doc can be committed and diffed like
 * any other file.
 *
 * Walks `CtrlMessageSchema.options` and `InnerMessageSchema.options` (both `z.discriminatedUnion`,
 * so `.options` is the array of per-`type` object schemas), reads each variant's `type` literal,
 * and emits a fenced JSON Schema block per message. `z.toJSONSchema` is called with
 * `{ unrepresentable: "any" }` because the protocol schemas embed byte types (`Bytes(32)` etc.)
 * that it otherwise refuses to convert.
 */
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { z } from "zod";
import { CtrlMessageSchema } from "../src/ctrl.js";
import { EnvelopeSchema, FRAME_LIMITS } from "../src/envelope.js";
import { InnerMessageSchema } from "../src/inner.js";

const OUT = join(import.meta.dirname, "..", "..", "..", "docs", "protocol.md");
const SPEC = "docs/superpowers/specs/2026-09-03-shellbell-design.md";

function toJson(schema: z.ZodTypeAny): string {
  return JSON.stringify(z.toJSONSchema(schema, { unrepresentable: "any" }), null, 2);
}

function typeOf(variant: z.ZodTypeAny): string {
  const shape = (variant as unknown as { shape: { type: { value: string } } }).shape;
  return shape.type.value;
}

function renderUnion<T extends z.ZodTypeAny>(title: string, options: readonly T[]): string {
  const parts = [`## ${title}\n`];
  for (const variant of options) {
    const t = typeOf(variant);
    parts.push(`### \`${t}\`\n\n\`\`\`json\n${toJson(variant)}\n\`\`\`\n`);
  }
  return parts.join("\n");
}

const byteLimitRows = [
  ["unauthenticated", `${FRAME_LIMITS.unauth} B (4 KB)`],
  ["any `ctrl` frame", `${FRAME_LIMITS.ctrl} B (16 KB)`],
  ["`e2e` from phone", `${FRAME_LIMITS.e2eFromPhone} B (64 KB)`],
  ["`e2e` from agent", `${FRAME_LIMITS.e2eFromAgent} B (1 MB)`],
]
  .map(([state, max]) => `| ${state} | ${max} |`)
  .join("\n");

const closeCodeRows = [
  ["4001", "auth failed"],
  ["4003", "bad pairing message"],
  ["4004", "unpaired"],
  ["4005", "superseded (duplicate identity connected)"],
  ["4400", "malformed frame"],
  ["4403", "forbidden for role"],
  ["4408", "unauth/pairing timeout"],
  ["4413", "frame too large"],
  ["4429", "rate limited"],
]
  .map(([code, meaning]) => `| \`${code}\` | ${meaning} |`)
  .join("\n");

const doc = `# Protocol reference

> Generated by \`packages/protocol/scripts/gen-protocol-doc.ts\` from the zod schemas in
> \`packages/protocol/src/ctrl.ts\`, \`packages/protocol/src/inner.ts\` and
> \`packages/protocol/src/envelope.ts\`. Do not hand-edit this file — run
> \`pnpm -F @shellbell/protocol gen:protocol-doc\` and commit the result. Full prose reference:
> \`${SPEC}\` §7 (Wire protocol).

## Envelope

Every WebSocket frame is binary CBOR (\`cborg\`, with \`{ ignoreUndefinedProperties: true }\` so
optional fields never appear on the wire), except protocol-level ping/pong control frames (agent
keepalive) and the literal text frames \`"ping"\` / \`"pong"\` (phone keepalive while
foregrounded). Every decoded object is validated with zod before use; invalid frames are dropped
(agent/app) or close the socket with \`4400\` (relay).

\`\`\`json
${toJson(EnvelopeSchema)}
\`\`\`

\`to\` is required when \`t\` is \`"e2e"\`. \`seq\` is used by \`e2e\` frames only (\`ctrl\` frames
send \`0\`). For \`e2e\` frames, \`body\` is \`{ n: bytes(24), c: bytes }\`; for \`ctrl\` frames it is
one of the Ctrl messages below.

## Byte limits

Enforced before decoding. Exceeding a limit closes the socket with \`4413\`.

| Socket state | Max frame |
|---|---|
${byteLimitRows}

## Rate limit

Per socket, a token bucket of **60 messages/s, burst 200** applies to every application message
(ctrl and e2e envelopes alike) — only WebSocket protocol-level ping/pong frames are exempt, and
those never reach the Durable Object. Exceeding it closes the socket with \`4429\`.

${renderUnion("Ctrl messages", CtrlMessageSchema.options)}
${renderUnion("Inner messages", InnerMessageSchema.options)}
## WebSocket close codes

| Code | Meaning |
|---|---|
${closeCodeRows}
`;

writeFileSync(OUT, doc);
console.log(`wrote ${OUT}`);
